package engine;

import DTO.codeHistory.CodeHistory;
import DTO.codeObj.CodeObj;
import DTO.techSpecs.TechSpecs;
import enigmaMachine.secret.Secret;
import javafx.util.Pair;

import javax.xml.bind.JAXBException;
import java.io.FileNotFoundException;
import java.util.List;

public interface Engine {
    boolean loadDataFromXML(String path);
    TechSpecs showTechSpecs();
    void setByAutoGeneratedCode();
    CodeObj getMachineCode();
    void setMachine(CodeObj machineCode);
    String processMsg(String msg);
    void resetMachine();
    void validateAndSetReflector(CodeObj underConstructionCode, String wantedReflectorID);
    void validateAndSetPlugs(CodeObj underConstructionCode, String plugs);
    void validateAndSetRotors(CodeObj underConstructionCode, String rotors);
    void validateAndSetRotorPositions(CodeObj underConstructionCode, String positionsOfRotors);
    List<CodeHistory> showCodeHistory();
}
