package engine;

import DTO.codeHistory.CodeHistory;
import DTO.codeObj.CodeObj;
import DTO.techSpecs.TechSpecs;
import enigmaMachine.secret.Secret;
import javafx.util.Pair;

import javax.xml.bind.JAXBException;
import java.io.FileNotFoundException;
import java.io.Serializable;
import java.util.List;

public interface Engine extends Serializable {
    boolean loadDataFromXML(String path);

    TechSpecs showTechSpecs();

    void setByAutoGeneratedCode();

    CodeObj getInitialCode(); //same as above...
    void setMachine(CodeObj machineCode);

    String processMsg(String msg);

    void resetMachine();

    void validateAndSetReflector(CodeObj underConstructionCode, String wantedReflectorID);

    void validateAndSetPlugs(CodeObj underConstructionCode, String plugs);

    void validateAndSetRotors(CodeObj underConstructionCode, String rotors);

    void validateAndSetRotorPositions(CodeObj underConstructionCode, String positionsOfRotors);

    List<CodeHistory> showCodeHistory();

    int getProcessedMsgsCnt();

    CodeObj getUpdatedCode();

    int getRotorsCount();

    int getTotalRotorAmount();

    int getReflectorCount();

    boolean isStockLoaded();
}