package testMain;

import DTO.codeObj.CodeObj;
import engine.Engine;
import DTO.techSpecs.TechSpecs;
import engine.TheEngine;
import enigmaMachine.secret.Secret;
import exceptions.XMLException.InvalidXMLException;
import exceptions.XMLException.XMLExceptionMsg;

public class Main {

    public static void main(String[] args) {
        Engine engine = new TheEngine();
        try{
            //return bool if loading succeed, later should notify ui for printing msg accordingly (success!)
            if(engine.loadDataFromXML("C:\\Downloads\\ex1-sanity-small.xml")) {
                //TechSpecs ts = engine.showTechSpecs();
                //System.out.println(ts.getTotalRotors());
                //System.out.println(ts.getNotchLocation());
            }
        }
        catch(InvalidXMLException e) {
            System.out.println(e.getMessage());
        }
        /*engine.setByAutoGeneratedCode();
        System.out.println("Machine code: " + engine.getMachineCode());*/
        CodeObj underConstruction = new CodeObj();
        engine.validateAndSetRotors(underConstruction, "1 2");
        engine.validateAndSetRotorPositions(underConstruction, "cc");
        engine.validateAndSetReflector(underConstruction, "I");
        engine.validateAndSetPlugs(underConstruction, "abcd");

        /*
        boolean valid = false;
        do{
            try{
                String s = "get from user";
                engine.validateAndSetRotors(underConstruction, s);
                valid = true;
            }
            catch(Exception e){
                System.out.println(e);
            }
        }while(!valid);
        */

        engine.setMachine(underConstruction);

        String myString = "AABBCCDDEEFF"; //-> CEEFBDFCDAAB
        String result = engine.processMsg(myString);
        result = engine.processMsg(myString);
        result = engine.processMsg(myString);

        System.out.println("input  -> " + myString);
        System.out.println("output -> " + result);

        /*engine.setByAutoGeneratedCode();
        result = engine.processMsg(myString);
        System.out.println("input  -> " + myString);
        System.out.println("output -> " + result);*/
        System.out.println(engine.showCodeHistory());

    }
}
